const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function game(){
 const elements=new Map(),storage=new Map();let seed=42;
 const math=Object.create(Math);math.random=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/2**32};
 const element=id=>{if(!elements.has(id))elements.set(id,{value:id==='gender'?'male':'',textContent:'',innerHTML:'',style:{},dataset:{},disabled:false,title:'',classList:{add(){},remove(){},toggle(){}},addEventListener(){},querySelectorAll(){return []},insertAdjacentHTML(_,x){this.innerHTML+=x},getBoundingClientRect(){return {left:0,width:500}},setPointerCapture(){},releasePointerCapture(){}});return elements.get(id)};
 const c={console,Math:math,Date,setTimeout,clearTimeout,alert(){throw Error('Unexpected popup')},document:{getElementById:element,querySelectorAll(){return []},querySelector(){return null},addEventListener(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)}};c.window=c;vm.createContext(c);
 const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');for(const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g))vm.runInContext(m[1],c);vm.runInContext(fs.readFileSync(path.join(__dirname,'../systems.js'),'utf8'),c);const run=code=>vm.runInContext(code,c);run('createLife()');return {run,storage};
}
const setup=`s.age=25;s.health=100;s.skill=100;s.wealth=100;s.prestige=100;Object.keys(s.skills).forEach(k=>s.skills[k]=100);s.experience={craft:100,state:100,trade:100,culture:100,military:100};s.pendingEventId=null;s.pendingDecision=null;s.monthsRemaining=12;`;

test('fresh life builds a persistent extended family and NPC personality model',()=>{const {run}=game();assert.ok(run('s.relatives.length>=4'));assert.ok(run('s.parents.every(n=>n.traits.length===2&&n.goal&&n.bonds&&Array.isArray(n.memories))'));assert.ok(run('s.relatives.some(n=>n.type==="Dede"||n.type==="Nine")'));});
test('adult decisions cannot be invoked by any child age',()=>{const {run}=game();for(let age=0;age<18;age++){run(setup+`s.age=${age};s.partner=normalizeNPC({age:18,alive:true,rel:100});`);for(const code of ['marry()','commitCrime(D.crimes[0].id)','militaryCall()','buyAsset("caravan_share")','takeRole("alp")','takeRole("smith")']){run(code);assert.equal(run('s.monthsRemaining'),12);assert.equal(run('s.wealth'),100);assert.equal(run('s.pendingDecision'),null);}}});
test('12 yearly action rights produce 12 decision cards and then reset next year',()=>{const {run}=game();for(let slot=1;slot<=12;slot++){run('guardianCare()');assert.equal(run('s.monthsRemaining'),12-slot);assert.equal(run('s.pendingEventContext.month'),slot);run('guardianCare();ageUp();load()');assert.equal(run('s.age'),0);assert.equal(run('s.monthsRemaining'),12-slot);run('chooseContextEvent(activeContextEvent().choices.findIndex(c=>!eventChoiceIssue(c)))');}assert.equal(run('s.eventArchive.length'),12);run('ageUp()');assert.equal(run('s.age'),1);assert.equal(run('s.monthsRemaining'),12);});
test('1 Yıl Geçir skips unused rights but still advances monthly systems',()=>{const {run}=game();run(setup+`s.pregnancy={remaining:3};s.married=true;s.partner=normalizeNPC({age:25,alive:true,rel:80,type:'Eş'});const a=s.age;passOneYear();window.nextAge=s.age;`);assert.equal(run('nextAge'),26);assert.equal(run('s.monthsRemaining'),12);});
test('every age and restricted context has an affordable card',()=>{const {run}=game();for(let age=0;age<=100;age++)for(const mode of ['free','captive',...(age>=18?['campaign','exile','captiveExile']:[])]){run(setup+`s.age=${age};s.wealth=0;s.captive=${mode.startsWith('captive')};s.exile=${mode==='exile'||mode==='captiveExile'};s.military.active=${mode==='campaign'};s.eventCooldowns=Object.fromEntries(EVENT_DECK.map(e=>[e.id,100]));triggerContextEvent(true,{kind:'wait',month:1});`);assert.ok(run('s.pendingEventId'),`${age} ${mode}`);assert.ok(run('activeContextEvent().choices.some(c=>!eventChoiceIssue(c))'));if(age<5)assert.equal(run('hasDirectAgency(activeContextEvent())'),false);}});
test('career entry and event offers enforce expertise and experience',()=>{const {run}=game();run(setup+'s.skills.craft=0;s.experience.craft=0;takeRole("smith")');assert.equal(run('s.monthsRemaining'),12);assert.equal(run('eventRequirementOK({req:"career:smith"})'),false);run('s.skills.craft=100;s.experience.craft=12');assert.equal(run('careerIssue(D.careers.find(r=>r.id==="smith"))'),'');});
test('training only unlocks at exact boundary',()=>{const {run}=game();run('s.age=4;train("horse")');assert.equal(run('s.monthsRemaining'),12);run('s.age=5;train("horse")');assert.equal(run('s.monthsRemaining'),11);});
test('third choice remains reachable without spending an additional action',()=>{const {run}=game();run(setup+`EVENT_DECK.push({id:'test_three',cat:'Oba',min:18,max:100,text:'Fixture',choices:[['A',{}],['B',{}],['C',{setFlag:'third'}]]});s.pendingEventId='test_three';s.pendingEventContext={age:25,year:s.year+25,month:1};finishSwipeChoice(1);`);assert.equal(run('s.decisionOffset'),1);run('finishSwipeChoice(1)');assert.equal(run('s.flags.third'),true);assert.equal(run('s.monthsRemaining'),12);});
test('NPC interaction changes trust and writes long-term memory',()=>{const {run}=game();run(setup);const before=run('s.parents[0].bonds.trust');run('interactNPC("parents",0,"spend")');assert.ok(run('s.parents[0].bonds.trust')>before);assert.ok(run('s.parents[0].memories.length>0'));assert.equal(run('s.parents[0].lastInteractionYear'),run('s.year+s.age'));});
test('rival reconciliation reduces grudge and can become friendship',()=>{const {run}=game();run(setup+`s.rivals=[normalizeNPC({name:'Rival',age:25,alive:true,rel:60,type:'Rakip',traits:['bagislayici','sakin'],bonds:{trust:40,respect:40,fear:0,grudge:18}})];`);run('interactNPC("rivals",0,"reconcile")');assert.equal(run('s.rivals.length'),0);assert.equal(run('s.friends.length'),1);assert.ok(run('s.friends[0].memories.some(m=>m.kind==="peace")'));});
test('targeted social events preview and persist consequences on the named NPC',()=>{const {run}=game();run(setup+`const n=s.parents[0];window.targetId=n.id;window.beforeRel=n.rel;s.pendingEventId='kin_help_request';s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:n.id};`);assert.ok(run('currentDecisionPayload().text.includes(s.parents[0].name)'));run('chooseContextEvent(0)');assert.ok(run('allNPCs().find(n=>n.id===targetId).rel>beforeRel'));assert.ok(run('allNPCs().find(n=>n.id===targetId).memories.length>0'));});
test('events requiring a missing target are filtered out',()=>{const {run}=game();run(setup+`s.siblings=[];const e=EVENT_DECK.find(x=>x.id==='sibling_path');e.cool=0;s.eventCooldowns[e.id]=0;`);assert.equal(run('eligibleContextEvents({kind:"wait",month:1}).some(e=>e.id==="sibling_path")'),false);});
test('campaign call persists and rejection is not restored',()=>{const {run}=game();run(setup+'militaryCall();load()');assert.equal(run('s.pendingDecision.id'),'campaign_call');run('chooseDecision(1);load()');assert.equal(run('s.pendingDecision'),null);assert.equal(run('s.flags.military_declined'),true);});
test('captivity and campaign cannot be bypassed; campaign still permits comrade interaction',()=>{const {run}=game();run(setup+'s.captive=true;buyAsset("horse");doPeriodActivity("market");takeRole("smith");addFriend()');assert.equal(run('s.monthsRemaining'),12);run(setup+'s.military.active=true;s.military.served=true;generateComrades();const r=s.military.comrades[0].rel;interactNPC("comrades",0,"spend")');assert.equal(run('s.monthsRemaining'),11);assert.ok(run('s.military.comrades[0].rel')>run('r'));});
test('inheritance preserves family network, calendar, siblings and months',()=>{const {run}=game();run(setup+`s.monthsRemaining=5;s.will='equal';s.children=[normalizeNPC({name:'Heir',gender:'male',age:8,alive:true}),normalizeNPC({name:'Sibling',gender:'female',age:5,alive:true})];s.assets=['horse','bow'];window.oldYear=s.year+s.age;window.oldID=s.id;window.oldGrand=s.parents[0].id;die();continueAsHeir(0);`);assert.equal(run('s.age'),8);assert.equal(run('s.year+s.age===oldYear'),true);assert.equal(run('s.monthsRemaining'),5);assert.equal(run('s.parents[0].id===oldID'),true);assert.equal(run('s.siblings[0].name'),'Sibling');assert.ok(run('s.relatives.some(n=>n.id===oldGrand)'));assert.equal(run('s.wealth'),50);assert.equal(run('s.assets.length'),1);});
test('legacy save migrates with backup and creates NPC depth fields',()=>{const {run,storage}=game();run(`s.version=2;delete s.relatives;delete s.parents[0].traits;delete s.parents[0].bonds;s.assets=['horse'];s.achievements=['family'];save();load()`);assert.ok(storage.has('yazgi_before_v5'));assert.equal(run('s.version'),5);assert.ok(run('Array.isArray(s.relatives)'));assert.ok(run('s.parents[0].traits.length===2&&s.parents[0].bonds'));});
test('health zero ends life in the current action slot',()=>{const {run}=game();run(setup+`s.health=1;s.ailments=[{id:'fever',remaining:2}];performAction({kind:'wait'},()=>{},'Test');`);assert.equal(run('s.alive'),false);assert.equal(run('s.monthsRemaining'),11);assert.equal(run('s.pendingEventId'),null);});
test('unaffordable choices do not change stats or consume the decision',()=>{const {run}=game();run(setup+`s.wealth=0;EVENT_DECK.push({id:'cost_test',cat:'Oba',min:18,max:100,text:'Fixture',choices:[['Pay',{wealth:-5,health:20}],['Wait',{}]]});s.pendingEventId='cost_test';chooseContextEvent(0);`);assert.equal(run('s.wealth'),0);assert.equal(run('s.pendingEventId'),'cost_test');});
test('child conditions and birthdays use actual NPC ages',()=>{const {run}=game();run(setup+`s.children=[normalizeNPC({age:0,alive:true,birthYear:s.year+s.age,birthMonth:6})];s.age++;familyTick();`);assert.equal(run('s.children[0].age'),0);assert.equal(run('eventRequirementOK({req:"hasAdultChild"})'),false);assert.equal(run('eventRequirementOK({req:"trainableChild"})'),false);run('monthlyTick(6,{kind:"wait"})');assert.equal(run('s.children[0].age'),1);});
test('season, action and unknown predicates are enforced',()=>{const {run}=game();run(setup);assert.equal(run('eventRequirementOK({req:"unknown"})'),false);assert.equal(run('eligibleContextEvents({kind:"wait",month:5}).some(e=>e.id==="winter_shortage")'),false);assert.equal(run('eligibleContextEvents({kind:"wait",month:1}).some(e=>e.id==="minor_wound")'),false);});
test('invalid save remains intact',()=>{const {run,storage}=game();storage.set('yazgi_full_v1','{"realm":"missing"}');run('console.error=()=>{};load()');assert.equal(storage.get('yazgi_full_v1'),'{"realm":"missing"}');});
test('20 annual NPC cycles keep relationship model in valid ranges',()=>{const {run}=game();run(setup);for(let i=0;i<20;i++)run('s.age++;familyTick()');assert.equal(run('allNPCs().every(n=>n.rel>=0&&n.rel<=100&&n.bonds.trust>=0&&n.bonds.trust<=100&&n.bonds.grudge>=0&&n.bonds.grudge<=100)'),true);});
test('legacy underage marriage is deferred without deleting the partner',()=>{const {run}=game();run(`s.age=12;s.married=true;s.partner=normalizeNPC({name:'Preserved',age:12,alive:true});s.version=2;save();load()`);assert.equal(run('s.married'),false);assert.equal(run('s.partner.name'),'Preserved');assert.equal(run('s.deferredMarriage'),true);assert.equal(run('canHaveChild()'),false);});
test('calendar remains on the event slot until the decision is resolved',()=>{const {run}=game();run('guardianCare()');assert.equal(run('currentMonth()'),1);run('chooseContextEvent(0)');assert.equal(run('currentMonth()'),2);});

test('NPC social graph seeds kinship and remains stable during rendering',()=>{const {run}=game();assert.ok(run('Array.isArray(s.socialLinks)&&s.socialLinks.length>0'));assert.ok(run('s.socialLinks.some(l=>l.tags.includes("kin")||l.tags.includes("spouse"))'));run('window.__pair=socialLinkBetween(s.parents[0],s.parents[1]);window.__score=__pair.score;renderFamily()');assert.equal(run('socialLinkBetween(s.parents[0],s.parents[1]).score'),run('__score'));});
test('NPC-to-NPC links can independently become friendship and rivalry',()=>{const {run}=game();run(setup+'if(!s.siblings.length)s.siblings.push(normalizeNPC({name:"Kin",age:20,alive:true,type:"Erkek kardeş",parentIds:s.parents.map(p=>p.id)}));window.__a=s.parents[0];window.__b=s.siblings[0];adjustSocialLink(__a,__b,{score:60,trust:20},"yakınlaştılar")');assert.ok(run('socialLinkBetween(__a,__b).tags.includes("friend")'));run('adjustSocialLink(__a,__b,{score:-120,grudge:80},"kavga")');assert.ok(run('socialLinkBetween(__a,__b).tags.includes("rival")'));});
test('high prestige autonomous NPC can reach Boy Beyi role',()=>{const {run}=game();run('window.__elite=normalizeNPC({name:"Elite",age:34,prestige:90,goal:"prestige",traits:["hirsli","gururlu"],alive:true})');assert.equal(run('npcCareerFor(__elite)'),'Boy Beyi');});
test('old friends and enemies survive succession as family contacts',()=>{const {run}=game();run(setup+'s.friends=[normalizeNPC({name:"OldFriend",age:40,alive:true,rel:85,type:"Dost"})];s.rivals=[normalizeNPC({name:"OldEnemy",age:41,alive:true,rel:20,type:"Rakip",bonds:{trust:10,respect:40,fear:0,grudge:70}})];s.children=[normalizeNPC({name:"Heir",gender:"male",age:12,alive:true})];s.monthsRemaining=0;die();continueAsHeir(0)');assert.ok(run('s.friends.some(n=>n.statusFlags.familyFriend)'));assert.ok(run('s.rivals.some(n=>n.statusFlags.familyEnemy)'));assert.ok(run('eventRequirementOK({req:"hasFamilyFriend"})'));assert.ok(run('eventRequirementOK({req:"hasFamilyEnemy"})'));});
test('rival friendship with close kin creates two NPC event targets',()=>{const {run}=game();run(setup+'window.__kin=s.parents[0];window.__r=normalizeNPC({name:"Rival",age:30,alive:true,rel:20,type:"Rakip"});s.rivals=[__r];adjustSocialLink(__kin,__r,{score:60,trust:20},"yakınlaştılar")');assert.ok(run('eventRequirementOK({req:"hasRivalKinLink"})'));run('window.__e=EVENT_DECK.find(e=>e.id==="rival_kin_bridge");window.__sel=eventTargetSelections(__e.target)[0];s.pendingEventId=__e.id;s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__sel.target.id,otherTargetId:__sel.other.id};window.__txt=currentDecisionPayload().text');assert.ok(run('__txt.includes("Rival")'));assert.ok(run('__txt.includes(__kin.name)'));});
test('story arc engine follows branching next steps and locks the same NPC',()=>{const {run}=game();run(setup+'s.rivals=[normalizeNPC({name:"Rival",age:26,alive:true,rel:20,type:"Rakip"})];window.__r=s.rivals[0];s.pendingEventId="rival_arc_challenge";s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__r.id};chooseContextEvent(0)');assert.equal(run('s.storyArcs.rivalry.nextEventId'),'rival_arc_escalation');assert.equal(run('eventTargetSelections("rival","rival_arc_escalation")[0].target.id'),run('__r.id'));run('s.pendingEventId="rival_arc_escalation";s.pendingEventContext={age:s.age,year:s.year+s.age,month:2,targetId:__r.id};chooseContextEvent(0)');assert.equal(run('s.storyArcs.rivalry.nextEventId'),'rival_arc_resolution');});
test('resolving personal rivalry converts the locked rival into a friend',()=>{const {run}=game();run(setup+'s.rivals=[normalizeNPC({name:"Rival",age:26,alive:true,rel:20,type:"Rakip"})];window.__r=s.rivals[0];s.pendingEventId="rival_arc_challenge";s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__r.id};chooseContextEvent(0);s.pendingEventId="rival_arc_escalation";s.pendingEventContext={age:s.age,year:s.year+s.age,month:2,targetId:__r.id};chooseContextEvent(0);s.pendingEventId="rival_arc_resolution";s.pendingEventContext={age:s.age,year:s.year+s.age,month:3,targetId:__r.id};chooseContextEvent(0)');assert.equal(run('s.storyArcs.rivalry.status'),'completed');assert.equal(run('s.rivals.some(n=>n.id===__r.id)'),false);assert.equal(run('s.friends.some(n=>n.id===__r.id)'),true);});
test('active story arc boosts only its expected next event',()=>{const {run}=game();run('s.age=15;s.pendingDecision=null;s.pendingEventId="smith_offer";s.pendingEventContext={age:15,year:s.year+15,month:1};chooseContextEvent(0)');assert.ok(run('eventEffectiveWeight(EVENT_DECK.find(e=>e.id==="smith_first_mistake"))')>run('eventEffectiveWeight(EVENT_DECK.find(e=>e.id==="horse_race"))'));assert.equal(run('storyArcEventAllowed(EVENT_DECK.find(e=>e.id==="smith_first_mistake"))'),true);assert.equal(run('storyArcEventAllowed(EVENT_DECK.find(e=>e.id==="smith_master_test"))'),false);});
test('dead participant closes a character-specific story instead of switching NPC',()=>{const {run}=game();run(setup+'s.rivals=[normalizeNPC({name:"Rival",age:26,alive:true,rel:20,type:"Rakip"})];window.__r=s.rivals[0];s.pendingEventId="rival_arc_challenge";s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__r.id};chooseContextEvent(0);__r.alive=false;ensureStoryArcs()');assert.equal(run('s.storyArcs.rivalry.status'),'abandoned');assert.equal(run('eventTargetSelections("rival","rival_arc_escalation").length'),0);});
test('exile return can be postponed and offered again without ending the arc',()=>{const {run}=game();run(setup+'s.exile=true;s.flags.exile_loyal=true;s.pendingEventId="exile_return";s.pendingEventContext={age:s.age,year:s.year+s.age,month:1};chooseContextEvent(1)');assert.equal(run('s.storyArcs.exile.status'),'active');assert.equal(run('s.storyArcs.exile.nextEventId'),'exile_return');assert.equal(run('EVENT_DECK.find(e=>e.id==="exile_return").once'),false);});

test('delayed consequences stay attached to the original NPC and resolve years later',()=>{const {run}=game();run(setup+'window.__child=normalizeNPC({name:"Child",gender:"male",age:12,alive:true,type:"Çocuk",birthYear:s.year+s.age-12,birthMonth:1});s.children=[__child];s.pendingEventId="child_training_choice";s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__child.id};chooseContextEvent(0);s.pendingEventId="child_training_conflict";s.pendingEventContext={age:s.age,year:s.year+s.age,month:2,targetId:__child.id};chooseContextEvent(0);s.pendingEventId="child_departure_choice";s.pendingEventContext={age:s.age,year:s.year+s.age,month:3,targetId:__child.id};chooseContextEvent(1);window.__delay=s.delayedEvents.find(x=>x.eventId==="child_path_consequence")');assert.equal(run('__delay.targetId'),run('__child.id'));assert.equal(run('__delay.payload.path'),'craft');run('s.age=__delay.dueYear-s.year;__child.age+=7;window.__ev=EVENT_DECK.find(e=>e.id==="child_path_consequence");window.__sel=eventTargetSelections(__ev.target,__ev.id)[0]');assert.equal(run('__sel.target.id'),run('__child.id'));run('s.pendingEventId=__ev.id;s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__child.id,delayedId:__sel.delayed.id,delayedPayload:__sel.delayed.payload};chooseContextEvent(0)');assert.equal(run('s.delayedEvents.find(x=>x.id===__delay.id).status'),'resolved');assert.equal(run('s.storyArcs.childpath.status'),'completed');assert.equal(run('__child.role'),'Demirci');});
test('household story follows the same spouse through five stages',()=>{const {run}=game();run(setup+'window.__g=s.gender==="male"?"female":"male";s.partner=normalizeNPC({name:"Ece",gender:__g,age:29,alive:true,rel:80,type:"Eş",bonds:{trust:80,respect:70,fear:0,grudge:0}});s.married=true;window.__p=s.partner');for(const [id,choice,month] of [['household_first_winter',1,1],['spouse_family_request',0,2],['household_work_balance',0,3],['household_trust_test',0,4]])run(`s.pendingEventId="${id}";s.pendingEventContext={age:s.age,year:s.year+s.age,month:${month},targetId:__p.id};chooseContextEvent(${choice})`);assert.equal(run('s.storyArcs.household.nextEventId'),'household_long_memory');assert.equal(run('s.storyArcs.household.participantIds[0]'),run('__p.id'));run('window.__d=s.delayedEvents.find(x=>x.eventId==="household_long_memory");s.age=__d.dueYear-s.year;window.__e=EVENT_DECK.find(e=>e.id==="household_long_memory");window.__sel=eventTargetSelections(__e.target,__e.id)[0]');assert.equal(run('__sel.target.id'),run('__p.id'));run('s.pendingEventId=__e.id;s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__p.id,delayedId:__sel.delayed.id,delayedPayload:__sel.delayed.payload};chooseContextEvent(0)');assert.equal(run('s.storyArcs.household.status'),'completed');});
test('scheduled future outcomes do not become eligible before their due year',()=>{const {run}=game();run(setup+'window.__n=normalizeNPC({name:"Child",age:12,alive:true,type:"Çocuk"});s.children=[__n];window.__d=scheduleDelayedEvent({id:"child_path_consequence",years:[6,6],payload:{path:"craft"}},{targetId:__n.id,sourceEventId:"fixture"});window.__e=EVENT_DECK.find(e=>e.id==="child_path_consequence")');assert.equal(run('delayedEventReady(__e)'),false);run('s.age=__d.dueYear-s.year');assert.equal(run('delayedEventReady(__e)'),true);});

test('rescued campaign comrade schedules long-term return and battlefield rescue',()=>{const {run}=game();run(setup+'s.age=28;s.military.served=true;s.military.active=true;s.military.campaigns=2;generateComrades();window.__m=s.military.comrades[0];__m.rel=70;normalizeBonds(__m);__m.bonds.trust=55;s.pendingEventId="military_comrade";s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__m.id};chooseContextEvent(0)');assert.equal(run('__m.statusFlags.warBond'),'saved');assert.ok(run('__m.bonds.trust')>55);assert.ok(run('s.delayedEvents.some(x=>x.eventId==="comrade_debt_returns"&&x.targetId===__m.id)'));assert.ok(run('s.delayedEvents.some(x=>x.eventId==="comrade_battle_rescue"&&x.targetId===__m.id)'));});
test('future battlefield rescue waits until a later active campaign and keeps the same comrade',()=>{const {run}=game();run(setup+'s.age=28;s.military.served=true;s.military.active=true;generateComrades();window.__m=s.military.comrades[0];s.pendingEventId="military_comrade";s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__m.id};chooseContextEvent(0);window.__d=s.delayedEvents.find(x=>x.eventId==="comrade_battle_rescue");s.age=__d.dueYear-s.year;s.military.active=false;window.__e=EVENT_DECK.find(x=>x.id==="comrade_battle_rescue")');assert.equal(run('eligibleContextEvents({kind:"wait",month:1}).some(x=>x.id==="comrade_battle_rescue")'),false);run('s.military.active=true;window.__sel=eventTargetSelections(__e.target,__e.id)[0]');assert.equal(run('__sel.target.id'),run('__m.id'));});
test('old campaign comrade can become a leader through the long-term comrade arc',()=>{const {run}=game();run(setup+'s.age=30;s.military.served=true;s.military.active=false;generateComrades();window.__m=s.military.comrades[0];__m.age=32;__m.prestige=70;window.__d=scheduleDelayedEvent({id:"comrade_debt_returns",years:[1,1],payload:{detail:"Eski sefer bağınız sürdü."}},{targetId:__m.id,sourceEventId:"fixture"});s.age=__d.dueYear-s.year;window.__e=EVENT_DECK.find(x=>x.id==="comrade_debt_returns");window.__sel=eventTargetSelections(__e.target,__e.id)[0];s.pendingEventId=__e.id;s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__m.id,delayedId:__sel.delayed.id,delayedPayload:__sel.delayed.payload};chooseContextEvent(0);window.__req=s.delayedEvents.find(x=>x.eventId==="comrade_request_aid"&&x.status==="pending");s.age=__req.dueYear-s.year;__e=EVENT_DECK.find(x=>x.id==="comrade_request_aid");__sel=eventTargetSelections(__e.target,__e.id)[0];s.pendingEventId=__e.id;s.pendingEventContext={age:s.age,year:s.year+s.age,month:2,targetId:__m.id,delayedId:__sel.delayed.id,delayedPayload:__sel.delayed.payload};chooseContextEvent(0);window.__rise=s.delayedEvents.find(x=>x.eventId==="comrade_rises"&&x.status==="pending");s.age=__rise.dueYear-s.year;__e=EVENT_DECK.find(x=>x.id==="comrade_rises");__sel=eventTargetSelections(__e.target,__e.id)[0];s.pendingEventId=__e.id;s.pendingEventContext={age:s.age,year:s.year+s.age,month:3,targetId:__m.id,delayedId:__sel.delayed.id,delayedPayload:__sel.delayed.payload};chooseContextEvent(0)');assert.equal(run('s.storyArcs.comradelegacy.status'),'completed');assert.ok(['Tarkan','Boy Beyi'].includes(run('__m.role')));assert.equal(run('s.friends.some(x=>x.id===__m.id)'),true);});
test('strong old comrade returns in the heir generation as a family friend',()=>{const {run}=game();run(setup+'s.age=40;s.military.served=true;generateComrades();window.__m=s.military.comrades[0];__m.rel=90;normalizeBonds(__m);__m.bonds.trust=90;s.children=[normalizeNPC({name:"Heir",gender:"male",age:10,alive:true})];s.monthsRemaining=0;die();continueAsHeir(0)');assert.ok(run('s.friends.some(x=>x.id===__m.id&&x.statusFlags.familyFriend)'));assert.ok(run('s.delayedEvents.some(x=>x.eventId==="legacy_comrade_visit"&&x.targetId===__m.id&&x.status==="pending")'));});

test('career profiles persist reputation mastery and earnings across work months',()=>{const {run}=game();run(setup+'s.role="Demirci";s.path="craft";s.experience.craft=30;s.skills.craft=100;window.__before=careerProfile("smith").months;workRole()');assert.equal(run('careerProfile("smith").months'),run('__before+1'));assert.ok(run('careerProfile("smith").mastery>=0'));assert.ok(run('careerProfile("smith").earnings>=0'));});
test('profession mentor contacts are real persistent NPCs in the global graph',()=>{const {run}=game();run(setup+'window.__u=careerContact("smith");window.__b=careerContact("scribe");window.__k=careerContact("caravan")');assert.ok(run('s.careerContacts.length>=3'));assert.equal(run('allNPCs().some(n=>n.id===__u.id)'),true);assert.equal(run('getFamilyGroup("careerContacts").some(n=>n.id===__b.id)'),true);assert.equal(run('careerContact("smith").id'),run('__u.id'));});
test('smith career story follows one master and completes seven stages',()=>{const {run}=game();run(setup+'s.age=30;s.wealth=200;s.prestige=80;s.experience.craft=30;s.skills.craft=100;window.__m=careerContact("smith")');for(const [id,ch] of [['smith_offer',0],['smith_first_mistake',0],['smith_master_test',0],['smith_customer_order',0],['smith_own_hearth',0],['smith_rival_contract',0],['smith_state_order',0]])run(`s.pendingEventId="${id}";s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__m.id};chooseContextEvent(${ch})`);assert.equal(run('s.storyArcs.smith.status'),'completed');assert.ok(run('careerProfile("smith").reputation>0'));assert.ok(run('s.delayedEvents.some(x=>x.eventId==="smith_old_work_returns")'));});
test('scribe career can branch into archive mastery without becoming envoy',()=>{const {run}=game();run(setup+'s.age=30;s.prestige=80;s.experience.state=40;s.skills.literacy=100;s.skills.speech=100;window.__m=careerContact("scribe")');for(const [id,ch] of [['scribe_offer',0],['scribe_copy',1],['scribe_record_dispute',1],['scribe_secret_record',0],['scribe_envoy_list',1],['scribe_archive_mastery',0]])run(`s.pendingEventId="${id}";s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__m.id};chooseContextEvent(${ch})`);assert.equal(run('s.storyArcs.scribe.status'),'completed');assert.equal(run('s.role'),'Bitigçi');});
test('caravan career alternative choices no longer dead-end the chain',()=>{const {run}=game();run(setup+'s.age=30;s.wealth=200;s.prestige=80;s.experience.trade=40;s.skills.trade=100;s.skills.riding=100;window.__m=careerContact("caravan")');for(const [id,ch] of [['caravan_invite',0],['caravan_first_crossing',1],['caravan_market',1],['caravan_loss',0],['caravan_partner',1],['caravan_route_rival',0],['caravan_master',0]])run(`s.pendingEventId="${id}";s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__m.id};chooseContextEvent(${ch})`);assert.equal(run('s.storyArcs.caravan.status'),'completed');assert.equal(run('s.flags.trader'),true);});
test('bard career grows from mentor to a delayed legacy song',()=>{const {run}=game();run(setup+'s.age=30;s.prestige=80;s.experience.culture=20;s.skills.speech=100;window.__m=careerContact("bard")');for(const id of ['bard_mentor_offer','bard_first_toy','bard_rival_verse','bard_patron_offer','bard_legacy_song'])run(`s.pendingEventId="${id}";s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__m.id};chooseContextEvent(0)`);assert.equal(run('s.storyArcs.bardcareer.status'),'completed');assert.ok(run('s.delayedEvents.some(x=>x.eventId==="bard_old_song_returns")'));});
test('merchant career includes work gate and delayed debt consequence',()=>{const {run}=game();run(setup+'s.age=30;s.role="Tüccar";s.experience.trade=30;s.skills.trade=100;s.careerProfiles.merchant={id:"merchant",months:4,reputation:20,mastery:20,earnings:0,orders:0,failures:0,streak:0,bestStreak:0,history:[]};window.__m=careerContact("merchant")');assert.equal(run('eventRequirementOK(EVENT_DECK.find(e=>e.id==="merchant_first_stall"))'),true);for(const [id,ch] of [['merchant_first_stall',0],['merchant_credit_request',0]])run(`s.pendingEventId="${id}";s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__m.id};chooseContextEvent(${ch})`);run('window.__d=s.delayedEvents.find(x=>x.eventId==="merchant_bad_debt"&&x.status==="pending");s.age=__d.dueYear-s.year;window.__e=EVENT_DECK.find(e=>e.id==="merchant_bad_debt");window.__sel=eventTargetSelections(__e.target,__e.id)[0];s.pendingEventId=__e.id;s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__m.id,delayedId:__sel.delayed.id,delayedPayload:__sel.delayed.payload};chooseContextEvent(0)');for(const id of ['merchant_market_name','merchant_partner_offer'])run(`s.pendingEventId="${id}";s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__m.id};chooseContextEvent(0)`);assert.equal(run('s.storyArcs.merchantcareer.status'),'completed');assert.ok(run('careerProfile("merchant").reputation>=20'));});
test('story arc v1 saves replay their archive into expanded v2 chains',()=>{const {run}=game();run('s.storyArcVersion=1;s.storyArcs={};s.eventArchive=[{id:"smith_offer",choice:0,age:13,year:s.year+13,month:1},{id:"smith_first_mistake",choice:0,age:14,year:s.year+14,month:2}];ensureStoryArcs()');assert.equal(run('s.storyArcVersion'),3);assert.equal(run('s.storyArcs.smith.nextEventId'),'smith_master_test');});

test('boy council rise keeps the same patron and rival through promotion',()=>{const {run}=game();run(setup+'s.age=32;s.health=100;s.wealth=200;s.skill=100;s.prestige=90;s.experience.state=60;Object.keys(s.skills).forEach(k=>s.skills[k]=100);window.__pair=eventTargetSelections("statePair","bey_request")[0];window.__patron=__pair.target;window.__rival=__pair.other');for(const [id,ch] of [['bey_request',0],['council_pasture_case',0],['council_levy_choice',0],['council_rival_challenge',0],['council_support_test',0]])run(`window.__e=EVENT_DECK.find(x=>x.id==="${id}");window.__sel=eventTargetSelections(__e.target,__e.id)[0];if(__sel.target.id!==__patron.id||__sel.other.id!==__rival.id)throw Error("state pair drift");s.pendingEventId=__e.id;s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__sel.target.id,otherTargetId:__sel.other.id};chooseContextEvent(${ch})`);assert.equal(run('s.storyArcs.councilrise.nextEventId'),'council_bey_nomination');assert.equal(run('eventRequirementOK(EVENT_DECK.find(x=>x.id==="council_bey_nomination"))'),true);run('window.__e=EVENT_DECK.find(x=>x.id==="council_bey_nomination");window.__sel=eventTargetSelections(__e.target,__e.id)[0];s.pendingEventId=__e.id;s.pendingEventContext={age:s.age,year:s.year+s.age,month:2,targetId:__sel.target.id,otherTargetId:__sel.other.id};chooseContextEvent(0)');assert.equal(run('s.role'),'Boy Beyi');assert.equal(run('s.storyArcs.councilrise.status'),'completed');});
test('boy bey role is locked behind council influence and trust even when skills are high',()=>{const {run}=game();run(setup+'s.age=32;s.skill=100;s.prestige=90;s.experience.state=60;Object.keys(s.skills).forEach(k=>s.skills[k]=100);s.stateCourt={initialized:true,influence:0,councilTrust:30,tribeSupport:45,rivalPressure:30,obligations:0,decisions:[]}');assert.ok(run('careerIssue(D.careers.find(r=>r.id==="bey")).includes("nüfuzu")'));run('s.stateCourt.influence=25;s.stateCourt.councilTrust=20');assert.ok(run('careerIssue(D.careers.find(r=>r.id==="bey")).includes("güveni")'));run('s.stateCourt.councilTrust=40');assert.equal(run('careerIssue(D.careers.find(r=>r.id==="bey"))'),'');});
test('beylik decisions schedule a judgment that returns years later',()=>{const {run}=game();run(setup+'s.age=36;s.health=100;s.wealth=200;s.skill=100;s.prestige=90;s.experience.state=60;Object.keys(s.skills).forEach(k=>s.skills[k]=100);ensureStateCircle();s.stateCourt.influence=70;s.stateCourt.councilTrust=70;s.role="Boy Beyi";window.__pair=eventTargetSelections("statePair","bey_first_petition")[0]');for(const [id,ch] of [['bey_first_petition',0],['bey_winter_reserve',0],['bey_kin_request',0],['bey_border_agreement',0]])run(`window.__e=EVENT_DECK.find(x=>x.id==="${id}");window.__sel=eventTargetSelections(__e.target,__e.id)[0];s.pendingEventId=__e.id;s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__sel.target.id,otherTargetId:__sel.other.id};chooseContextEvent(${ch})`);assert.equal(run('s.storyArcs.beyrule.nextEventId'),'bey_old_judgment');assert.ok(run('s.delayedEvents.some(x=>x.eventId==="bey_old_judgment"&&x.status==="pending")'));run('window.__d=s.delayedEvents.find(x=>x.eventId==="bey_old_judgment"&&x.status==="pending");s.age=__d.dueYear-s.year;window.__e=EVENT_DECK.find(x=>x.id==="bey_old_judgment");window.__sel=eventTargetSelections(__e.target,__e.id)[0];s.pendingEventId=__e.id;s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__sel.target.id,otherTargetId:__sel.other.id,delayedId:__sel.delayed.id,delayedPayload:__sel.delayed.payload};chooseContextEvent(1)');assert.equal(run('s.storyArcs.beyrule.status'),'completed');assert.equal(run('s.delayedEvents.find(x=>x.id===__d.id).status'),'resolved');});
test('state work and yearly ticks evolve influence and rival pressure',()=>{const {run}=game();run(setup+'s.age=34;s.role="Boy Beyi";s.health=100;s.skill=100;s.prestige=90;s.experience.state=60;Object.keys(s.skills).forEach(k=>s.skills[k]=100);ensureStateCircle();s.stateCourt.influence=30;s.stateCourt.councilTrust=45;s.stateCourt.rivalPressure=30;window.__before=s.stateCourt.influence;workRole()');assert.ok(run('s.stateCourt.influence>=__before'));run('window.__rp=s.stateCourt.rivalPressure;stateYearTick()');assert.ok(run('s.stateCourt.rivalPressure>=0&&s.stateCourt.rivalPressure<=100'));});
test('story arc v2 saves migrate into v3 and replay old council events',()=>{const {run}=game();run('s.storyArcVersion=2;s.storyArcs={};s.eventArchive=[{id:"bey_request",choice:0,age:25,year:s.year+25,month:2}];ensureStoryArcs()');assert.equal(run('s.storyArcVersion'),3);assert.equal(run('s.storyArcs.councilrise.nextEventId'),'council_pasture_case');});

test('persistent health profile tracks illness treatment and a healer NPC',()=>{const {run}=game();run(setup+'s.age=30;s.health=80;s.wealth=30;s.pendingEventId="sickness";s.pendingEventContext={age:s.age,year:s.year+s.age,month:1};chooseContextEvent(0)');assert.ok(run('s.ailments.some(x=>x.id==="fever"&&x.severity>=1)'));assert.equal(run('s.flags.health_crisis_ready'),true);run('window.__h=healthHealer()');assert.equal(run('__h.statusFlags.healthHealer'),true);assert.ok(run('allNPCs().some(n=>n.id===__h.id)'));});
test('healing story follows the same healer through recovery',()=>{const {run}=game();run(setup+'s.age=30;s.health=70;s.wealth=30;acquireAilment("fever",{severity:2,duration:3,source:"test"});s.flags.health_crisis_ready=true;window.__e=EVENT_DECK.find(e=>e.id==="health_crisis");window.__sel=eventTargetSelections(__e.target,__e.id)[0];window.__h=__sel.target;s.pendingEventId=__e.id;s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,targetId:__h.id};chooseContextEvent(1)');assert.equal(run('s.storyArcs.healingroad.nextEventId'),'health_followup');assert.ok(run('s.healthProfile.healerVisits>=1'));run('window.__e=EVENT_DECK.find(e=>e.id==="health_followup");window.__sel=eventTargetSelections(__e.target,__e.id)[0]');assert.equal(run('__sel.target.id'),run('__h.id'));});
test('battle wound creates serious ailment scar and a years-later flare',()=>{const {run}=game();run(setup+'s.age=30;s.military.served=true;s.military.active=true;s.health=100;s.pendingEventId="battle_wound";s.pendingEventContext={age:s.age,year:s.year+s.age,month:1};chooseContextEvent(1)');assert.ok(run('s.ailments.some(x=>x.id==="deep_wound"&&x.severity===3)'));assert.ok(run('s.healthProfile.scars.some(x=>x.kind==="battle"&&x.severity===2)'));assert.ok(run('s.delayedEvents.some(x=>x.eventId==="old_wound_flare"&&x.status==="pending")'));assert.ok(run('physicalHealthIssue({kind:"training",id:"wrestling"}).length>0'));});
test('old battle wound can return decades later and resolve its delayed record',()=>{const {run}=game();run(setup+'s.age=30;window.__scar=addScar("battle",2,"fixture");window.__d=s.delayedEvents.find(x=>x.eventId==="old_wound_flare"&&x.status==="pending");s.age=Math.max(40,__d.dueYear-s.year);window.__e=EVENT_DECK.find(e=>e.id==="old_wound_flare");window.__sel=eventTargetSelections(__e.target,__e.id)[0];s.pendingEventId=__e.id;s.pendingEventContext={age:s.age,year:s.year+s.age,month:1,delayedId:__sel.delayed.id,delayedPayload:__sel.delayed.payload};chooseContextEvent(0)');assert.equal(run('s.delayedEvents.find(x=>x.id===__d.id).status'),'resolved');assert.ok(run('s.ailments.some(x=>x.id==="old_wound")'));});
test('rest and healer care shorten active ailments while healer care also reduces severity',()=>{const {run}=game();run(setup+'s.age=30;s.wealth=20;acquireAilment("deep_wound",{severity:3,duration:7,source:"test"});window.__before=s.ailments[0].remaining;healthAction("rest")');assert.ok(run('s.ailments[0].remaining<__before'));run('s.pendingEventId=null;s.pendingDecision=null;s.monthsRemaining=12;window.__sev=s.ailments[0].severity;healthAction("healer")');assert.ok(run('s.ailments.length===0||s.ailments[0].severity<__sev'));assert.ok(run('s.healthProfile.healerVisits>=1'));});
test('health burden and frailty contribute to annual mortality risk',()=>{const {run}=game();run(setup+'s.age=70;s.health=35;addScar("battle",2,"old");addScar("fall",1,"old2");healthAgeTick();window.__risk=healthRisk()');assert.ok(run('s.healthProfile.frailty>0'));assert.ok(run('__risk>0.1'));});
test('v4 saves migrate to v5 with health profile and a dedicated backup',()=>{const {run,storage}=game();run('s.version=4;delete s.healthProfile;save();load()');assert.equal(run('s.version'),5);assert.ok(storage.has('yazgi_before_v5'));assert.ok(run('s.healthProfile&&Array.isArray(s.healthProfile.scars)'));});
