const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function game(){
 const elements=new Map(),storage=new Map();let seed=42;
 const math=Object.create(Math);math.random=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/2**32};
 const element=id=>{if(!elements.has(id))elements.set(id,{value:id==='gender'?'male':'',textContent:'',innerHTML:'',style:{},dataset:{},classList:{add(){},remove(){},toggle(){}},addEventListener(){},querySelectorAll(){return []},insertAdjacentHTML(_,x){this.innerHTML+=x},getBoundingClientRect(){return {left:0,width:500}},setPointerCapture(){},releasePointerCapture(){}});return elements.get(id)};
 const c={console,Math:math,Date,setTimeout,clearTimeout,alert(){throw Error('Unexpected popup')},document:{getElementById:element,querySelectorAll(){return []},querySelector(){return null},addEventListener(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)}};c.window=c;vm.createContext(c);
 const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');for(const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g))vm.runInContext(m[1],c);vm.runInContext(fs.readFileSync(path.join(__dirname,'../systems.js'),'utf8'),c);const run=code=>vm.runInContext(code,c);run('createLife()');return {run,storage};
}
const setup=`s.age=25;s.health=100;s.skill=100;s.wealth=100;s.prestige=100;Object.keys(s.skills).forEach(k=>s.skills[k]=100);s.experience={craft:100,state:100,trade:100,culture:100,military:100};s.pendingEventId=null;s.pendingDecision=null;s.monthsRemaining=12;`;
test('adult decisions cannot be invoked by any child age',()=>{const {run}=game();for(let age=0;age<18;age++){run(setup+`s.age=${age};s.partner=normalizeNPC({age:18,alive:true,rel:100});`);for(const code of ['marry()','commitCrime(D.crimes[0].id)','militaryCall()','buyAsset("caravan_share")','takeRole("alp")','takeRole("smith")']){run(code);assert.equal(run('s.monthsRemaining'),12);assert.equal(run('s.wealth'),100);assert.equal(run('s.pendingDecision'),null);}}});
test('12 actions and 12 same-month decisions survive save/reload; no extra action',()=>{const {run}=game();for(let month=1;month<=12;month++){run('guardianCare()');assert.equal(run('s.monthsRemaining'),12-month);assert.equal(run('s.pendingEventContext.month'),month);run('guardianCare();ageUp();load()');assert.equal(run('s.age'),0);assert.equal(run('s.monthsRemaining'),12-month);assert.equal(run('s.pendingEventContext.month'),month);assert.equal(run('currentDecisionPayload().title'),'Ailenin / Bakıcının Kararı');run('chooseContextEvent(activeContextEvent().choices.findIndex(c=>!eventChoiceIssue(c)))');}assert.equal(run('s.eventArchive.length'),12);run('ageUp()');assert.equal(run('s.age'),1);assert.equal(run('s.monthsRemaining'),12);});
test('every age and restricted context has an affordable card',()=>{const {run}=game();for(let age=0;age<=100;age++)for(const mode of ['free','captive',...(age>=18?['campaign','exile','captiveExile']:[])]){run(setup+`s.age=${age};s.wealth=0;s.captive=${mode.startsWith('captive')};s.exile=${mode==='exile'||mode==='captiveExile'};s.military.active=${mode==='campaign'};s.eventCooldowns=Object.fromEntries(EVENT_DECK.map(e=>[e.id,100]));triggerContextEvent(true,{kind:'wait',month:1});`);assert.ok(run('s.pendingEventId'),`${age} ${mode}`);assert.ok(run('activeContextEvent().choices.some(c=>!eventChoiceIssue(c))'));if(age<5)assert.equal(run('hasDirectAgency(activeContextEvent())'),false);}});
test('career entry and event offers enforce expertise and experience',()=>{const {run}=game();run(setup+'s.skills.craft=0;s.experience.craft=0;takeRole("smith")');assert.equal(run('s.monthsRemaining'),12);assert.equal(run('eventRequirementOK({req:"career:smith"})'),false);run('s.skills.craft=100;s.experience.craft=12');assert.equal(run('careerIssue(D.careers.find(r=>r.id==="smith"))'),'');});
test('training only unlocks at exact boundary',()=>{const {run}=game();run('s.age=4;train("horse")');assert.equal(run('s.monthsRemaining'),12);run('s.age=5;train("horse")');assert.equal(run('s.monthsRemaining'),11);});
test('third choice remains reachable without spending an additional month',()=>{const {run}=game();run(setup+`EVENT_DECK.push({id:'test_three',cat:'Oba',min:18,max:100,text:'Fixture',choices:[['A',{}],['B',{}],['C',{setFlag:'third'}]]});s.pendingEventId='test_three';s.pendingEventContext={age:25,year:s.year+25,month:1};finishSwipeChoice(1);`);assert.equal(run('s.decisionOffset'),1);run('finishSwipeChoice(1)');assert.equal(run('s.flags.third'),true);assert.equal(run('s.monthsRemaining'),12);});
test('campaign call persists and rejection is not restored',()=>{const {run}=game();run(setup+'militaryCall();load()');assert.equal(run('s.pendingDecision.id'),'campaign_call');run('chooseDecision(1);load()');assert.equal(run('s.pendingDecision'),null);assert.equal(run('s.flags.military_declined'),true);});
test('captivity and campaign cannot be bypassed through public handlers',()=>{const {run}=game();for(const state of ['s.captive=true','s.military.active=true']){run(setup+state);run('buyAsset("horse");doPeriodActivity("market");takeRole("smith");addFriend()');assert.equal(run('s.monthsRemaining'),12);assert.equal(run('s.wealth'),100);}});
test('inheritance preserves family, calendar, siblings and months',()=>{const {run}=game();run(setup+`s.monthsRemaining=5;s.will='equal';s.children=[normalizeNPC({name:'Heir',gender:'male',age:8,alive:true}),normalizeNPC({name:'Sibling',gender:'female',age:5,alive:true})];s.assets=['horse','bow'];window.oldYear=s.year+s.age;window.oldID=s.id;die();continueAsHeir(0);`);assert.equal(run('s.age'),8);assert.equal(run('s.year+s.age===oldYear'),true);assert.equal(run('s.monthsRemaining'),5);assert.equal(run('s.parents[0].id===oldID'),true);assert.equal(run('s.siblings[0].name'),'Sibling');assert.equal(run('s.wealth'),50);assert.equal(run('s.assets.length'),1);});
test('legacy save migrates with backup and preserves features',()=>{const {run,storage}=game();run(`s.version=1;delete s.experience;delete s.ailments;delete s.pendingEventContext;s.assets=['horse'];s.achievements=['family'];save();load()`);assert.ok(storage.has('yazgi_before_v2'));assert.equal(run('s.version'),2);assert.equal(run('s.assets[0]'),'horse');assert.equal(run('s.achievements[0]'),'family');});
test('health zero ends life in the current month',()=>{const {run}=game();run(setup+`s.health=1;s.ailments=[{id:'fever',remaining:2}];passOneMonth()`);assert.equal(run('s.alive'),false);assert.equal(run('s.monthsRemaining'),11);assert.equal(run('s.pendingEventId'),null);});
test('unaffordable choices do not change stats or consume the decision',()=>{const {run}=game();run(setup+`s.wealth=0;EVENT_DECK.push({id:'cost_test',cat:'Oba',min:18,max:100,text:'Fixture',choices:[['Pay',{wealth:-5,health:20}],['Wait',{}]]});s.pendingEventId='cost_test';chooseContextEvent(0);`);assert.equal(run('s.wealth'),0);assert.equal(run('s.pendingEventId'),'cost_test');});
test('child conditions and birthdays use actual NPC ages',()=>{const {run}=game();run(setup+`s.children=[normalizeNPC({age:0,alive:true,birthYear:s.year+s.age,birthMonth:6})];s.age++;familyTick();`);assert.equal(run('s.children[0].age'),0);assert.equal(run('eventRequirementOK({req:"hasAdultChild"})'),false);assert.equal(run('eventRequirementOK({req:"trainableChild"})'),false);run('monthlyTick(6,{kind:"wait"})');assert.equal(run('s.children[0].age'),1);});
test('season, action and unknown predicates are enforced',()=>{const {run}=game();run(setup);assert.equal(run('eventRequirementOK({req:"unknown"})'),false);assert.equal(run('eligibleContextEvents({kind:"wait",month:5}).some(e=>e.id==="winter_shortage")'),false);assert.equal(run('eligibleContextEvents({kind:"wait",month:1}).some(e=>e.id==="minor_wound")'),false);});
test('invalid save remains intact',()=>{const {run,storage}=game();storage.set('yazgi_full_v1','{"realm":"missing"}');run('console.error=()=>{};load()');assert.equal(storage.get('yazgi_full_v1'),'{"realm":"missing"}');});
test('720 monthly transitions maintain valid pending cards and nonnegative money',()=>{const {run}=game();for(let i=0;i<720;i++){run(`if(!s.alive){createLife();}s.health=100;if(s.pendingDecision)chooseDecision(1);if(s.monthsRemaining===0)ageUp();if(s.pendingDecision)chooseDecision(1);if(!s.alive)createLife();passOneMonth();`);assert.ok(run('s.pendingEventId'),`month ${i}`);run('chooseContextEvent(activeContextEvent().choices.findIndex(c=>!eventChoiceIssue(c)))');assert.ok(run('s.wealth>=0'));assert.equal(run('s.pendingEventId'),null);}});
test('legacy underage marriage is deferred without deleting the partner',()=>{const {run}=game();run(`s.age=12;s.married=true;s.partner=normalizeNPC({name:'Preserved',age:12,alive:true});s.version=1;save();load()`);assert.equal(run('s.married'),false);assert.equal(run('s.partner.name'),'Preserved');assert.equal(run('s.deferredMarriage'),true);assert.equal(run('canHaveChild()'),false);});
test('calendar remains on the event month until the decision is resolved',()=>{const {run}=game();run('guardianCare()');assert.equal(run('currentMonth()'),1);run('chooseContextEvent(0)');assert.equal(run('currentMonth()'),2);});
